package BLL;

public enum MessageType {
    NORMAL_MESSAGE, // 普通消息
    ADD_FRIEND_REQUEST, // 加好友
    DELETE_FRIEND_REQUEST, // 删好友
    LOGIN_REQUEST, // 登录请求
    CREATE_ACCOUNT_REQUEST, //新建账户请求
    LOGIN_SUCCESS, //登陆成功
    LOGIN_FAILED_ACCOUNT_NOT_FOUND,
    LOGIN_FAILED_PASSWORD_INCORRECT,
    CREATE_ACCOUNT_SUCCESS,
    CREATE_ACCOUNT_FAILED_ACCOUNT_EXIST,
}
